namespace ResumeRAG.Models;

/// <summary>
/// Pairs a text chunk with its vector embedding for storage and retrieval.
/// This is the primary unit stored in the JSON vector store.
/// </summary>
public class ChunkEmbedding
{
    /// <summary>Unique chunk identifier matching the source TextChunk.Id.</summary>
    public string ChunkId { get; set; } = "";

    /// <summary>The original text content of the chunk.</summary>
    public string Text { get; set; } = "";

    /// <summary>Source PDF file name (not full path, for readability).</summary>
    public string SourceFile { get; set; } = "";

    /// <summary>Sequential index within the source document.</summary>
    public int ChunkIndex { get; set; }

    /// <summary>
    /// The vector embedding generated by the embedding model.
    /// For nomic-embed-text this is a 768-dimensional float array.
    /// </summary>
    public float[] Embedding { get; set; } = [];
}
